/***** DO NOT EDIT THIS FILE *****/
// HelloWordProject.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var HelloWordProject = {};

/*** script -- HelloWordTest ***/
HelloWordProject.HelloWordTest = function(app) {
	MT.Script.call(this, app, "HelloWordTest.mt");
};

HelloWordProject.HelloWordTest.prototype = new MT.Script;

HelloWordProject.HelloWordTest.prototype.call = function(user) {
	//run: HelloWordTest.mt
	MT.Script.prototype.call(this, user);
};

MT.Application.prototype.helloWordTest = function() {
	return new HelloWordProject.HelloWordTest(this);
};

/*** script -- testDriverScript ***/
HelloWordProject.testDriverScript = function(app) {
	MT.Script.call(this, app, "testDriverScript.mt");
};

HelloWordProject.testDriverScript.prototype = new MT.Script;

HelloWordProject.testDriverScript.prototype.call = function() {
	//run: testDriverScript.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.testDriverScript = function() {
	return new HelloWordProject.testDriverScript(this);
};

